markdown: kramdown
remote_theme: minima
plugins:
  - jekyll-sitemap
kramdown:
  input: GFM
  hard_wrap: false
title: テスト用ページ
description: 【テスト用】Kindle本のセール・高還元情報まとめ
timezone: Asia/Tokyo
github:
  is_project_page: true